# Plugins
gems:
- jekyll-sitemap
safe: false

# Build Settings
markdown: kramdown
permalink: pretty
exclude: ['/automation/', 'README.md', 'LICENSE.txt', 'CNAME']

# Site Settings
title: "Best of Web - Le meilleur de chaque meetup web de Paris"
email: "bestofweb-orga@googlegroups.com"
description: "Best of Web - Le meilleur de chaque meetup web de Paris"
baseurl: ""
url: "http://bestofweb.paris"
# googleAnalyticsTrackingId: "UA-59690867-1"
# googleAnalyticsSiteUrl: "bestofweb.paris"
# siteVerification: "b9imDOrFawXaBXCC4r3uJDdswSYcalD-wWpMYhFq-no"

# Head
metaKeywords: "event, best of web, paris"
twitterAccount: "@bestofwebconf"
socialImageSrcGooglePlus: "/img/seo/sharing-google-plus.png"
socialImageSrcTwitter: "/img/seo/sharing-twitter.png"
socialImageSrcFacebook: "/img/seo/sharing-facebook.png"

# Call For Papers
cfpUrl: ""

# Navigation
navigationLinks:
 - {permalink: "/", text: "Home"}
 - {permalink: "/#tickets", text: "Tickets"}
 - {permalink: "/#getting-there", text: "S’y rendre"}
 - {permalink: "/#sponsors", text: "Sponsors"}
 - {permalink: "/#partners", text: "Partenaires"}
 - {permalink: "/#organizers", text: "L’équipe"}
 - {permalink: "/2015/", text: "2015"}
 - {permalink: "/2016/", text: "2016"}
bottomNavigationLinks:
 - {link: "", text: "Become a speaker"}
rightNavigationButtons:
 - {link: "", text: "Become a speaker"}

# Hero Block
heroImage: "hero.jpg"
heroTitle: "Best of Web <typeout> 2017"
eventDate: "8 & 9 Juin 2017"
typeoutTextValues: '"", "Angular Paris", "Angular X Paris", "Paris WebComponents", "D3.js Paris", "Node.js Paris", "CSS Paris", "Meteor Paris", "ReactJS Paris", "Paris API", "Loopback Paris", "Elm Paris", "Js-Star.Paris", "Vuejs Paris", "Paris Scala UG", "Paris.js", "Paris TypeScript", "HumanTalks Paris", "Tech Lunch", "Hybride Mobile Paris"'
typeoutFallback: ""
heroButtons:
 - {link: "", text: "Become a speaker"}
 - {permalink: "/#tickets", text: "Buy tickets"}

# About Block
aboutTitle: "About Best of Web"
aboutBlock:
 - {title: "Conference", image: "conference.jpg", text: "The biggest Google related event in the country carefully crafted for you by GDG community! Awesome speakers and lots of fun!" }
 - {title: "Workshops", image: "workshop.jpg", text: "Full-day of workshops, hands-on experience, hacking and debugging. Come and tame your favourite technology!" }
 - {title: "Hackathon", image: "hackathon.jpg", text: "Full-day freestyle hackathon! Want some real team building on friday? Grab your team and join our hackathon!" }

# Statistic Block
statisticBlockImage: "statistic.jpg"
statisticBlock:
 - {count: "500", specialCharacter: "+", info: "participants", detail: "pour une conférence à l’ambiance Meetup"}
 - {count: "19", specialCharacter: "", info: "meetups", detail: "qui se réunissent"}
 - {count: "13", specialCharacter: "", info: "speakers", detail: "qui font partie de la communauté"}
 - {count: "2", specialCharacter: "", info: "jours", detail: "1 journée formation / 1 journée conférence"}

# Rockstar Speakers Block
# TODO: rename -> speakers (or delete)
rockstarSpeakersImage: "rockstar-speakers.jpg"
rockstarSpeakersCount: 4
rockstarSpeakersTitle: "Rockstar speakers"
rockstarSpeakersButtonText: "See all speakers"

# Location Block
locationBlockTitle: "S’y rendre"
eventLocationName: "La Grande Crypte"
eventLocationLink: "http://cabinet.kinopalace.lviv.ua/showtimes/"
eventStreetAddress: "69bis rue Boissière"
eventAddressLocality: "Paris"
eventAddressLocalityRegion: ""
eventPostalCode: "75116"
eventAddressCountry: ""
eventStartTime: "2017-06-09T08:00"
eventDoorTime: "08:00"
eventEndTime: "2014-10-25T18:00"
eventPlaceCoordinates: "48.8684535, 2.2828132"
mapCenterCoordinates: "48.8684535, 2.2828132"
mapMobileCenterCoordinates: "48.8684535, 2.2828132"

# Partners Block
organizersTitle: "Sponsors"
partnersTitle: "Partenaires"
partnersC4sponsorsButton: "Devenez sponsor"
sponsoringDocUrl: "/assets/BOW2017-Sponsoring.pdf"

# Tickets Block
ticketsTitle: "Tickets Conférence (9 juin)"
ticketsInfo: "Les tickets de conférence vous donnent accès à la journée de conférence du vendredi 9 juin."
ticketsOffers:
 -
  name: "Regular"
  price: "50"
  priceCurrency: "€"
  # ticketsNumber: "150"
  # ribbon: "-20%"
  buyButtonLink: "https://checkout.eventlama.com/#/events/best-of-web-2017/tickets"
  buyButtonText: "Je prends"
  ticketContentList: ["Accès aux conférences du vendredi 9 juin", "Même à ce prix là, ça reste cadeau !"]
  # validFrom: "2016-08-25T10:00"
  # validThrough: "2016-09-30T23:59"
  # soldOut: true
  # soldOutText: "Sold Out"
 -
  name: "Formation professionnelle"
  price: "150"
  priceCurrency: "€ (HT)"
  buyButtonLink: "http://www.oxiane.com/inscription-best-of-web/"
  buyButtonText: "Je m’inscris"
  ticketContentList: ["Accès aux conférences du vendredi 9 juin", "Via notre partenaire de formation OXiane"]

# Footer
socialLinks:
 - {link: "https://plus.google.com/b/102444623953913144164", icon: "google-plus"}
 - {link: "https://twitter.com/intent/user?screen_name=GDGLviv", icon: "twitter"}
 - {link: "https://facebook.com/GDGLviv", icon: "facebook"}
 - {permalink: "/feed.xml", icon: "rss"}
footerBlocks:
 -
  title: "Links"
  links:
   - {link: "http://gdg.org.ua", text: "GDG.org.ua"}
   - {link: "https://developers.google.com", text: "Google Developers"}
 -
  title: "Contacts"
  links:
   - {link: "mailto:lviv@gdg.org.ua", text: "lviv@gdg.org.ua"}
 -
  title: "FAQ"
  links:
   - {permalink: "/cod/", text: "Code of Conduct"}

# Speakers List Block
showSessions: true

# Team Block
teamBlockTitle: "About us"
aboutUs: "Google's services have become synonymous with simple things online. Number of technological innovations and IT industries in which Google is creating new products is enormous. It's hard to get to know all of them, but realistic. This is why people have started to gather in small local groups and share their experience. Later, the following groups have been called Google Developer Groups. GDGs can take many forms -- from just a few people getting together to watch some videos, to large gatherings with demos, tech talks, hackathons and conferences."

# Logistics Find Way Block
findWayTitle: "Find your way here"
findWayDistance: "Distance"
findWayDriving: "DRIVING"
findWayWalking: "WALKING"
findWayBicycling: "BICYCLING"
findWayTransit: "TRANSIT"
findWayFindFlight: "Find Flight"
logisticsMapCenterCoordinates: "49.056728, 3.117289"
logisticsMapMobileCenterCoordinates: "48.335365, 23.711648"
logisticsMapAutoDirections: false
viewOnMap: "Voir sur Google Maps"

# Logistics Direction Details Block
directionDetailsImage: "direction-details.jpg"
directionDetailsTitle: "Get around Lviv"
directionDetailsCards:
 - {title: "From the Airport", information: 'Airport is right at the city border. It is easily reachable by car, public transport or taxi. More information is available at <a href="http://lwo.aero/en/transport">airport website</a>.'}
 - {title: "Public Transit", information: 'Google Transit is available in Lviv. So you can find your way in Google Maps. Moreover, you can download any of the offline public transit apps available for Lviv.'}
 - {title: "Hotels", information: 'Lviv has lots of great hotels and hostels. More information will be available later.'}
directionDetailsWideCards:
 -
  title: "Questions?"
  subCards:
   -
    title: "Hotels"
    links:
     - {link: "https://plus.google.com/b/102444623953913144164", text: "InterContinental"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "The Hotel Rex"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Westin Market Street"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Hotel Adagio"}
   -
    title: "Registration"
    links:
     - {link: "https://plus.google.com/b/102444623953913144164", text: "InterContinental"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "The Hotel Rex"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Westin Market Street"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Hotel Adagio"}
   -
    title: "Attendance Details"
    links:
     - {link: "https://plus.google.com/b/102444623953913144164", text: "InterContinental"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "The Hotel Rex"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Westin Market Street"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Hotel Adagio"}
